// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avzecesbavertvgdazed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2emVjZXNiYXZlcnR2Z2RhemVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTE3MjgsImV4cCI6MjA2Njk2NzcyOH0.C2uSXenQFs71QwqL_YKge5958y1Nq7iPplyIQ8nX3AY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});